"use client";

import { useEffect, useRef } from "react";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { MessageSquare, Code, Zap, Settings } from "lucide-react";

if (typeof window !== "undefined") {
  gsap.registerPlugin(ScrollTrigger);
}

const features = [
  {
    icon: MessageSquare,
    title: "Natural Language Queries",
    description: "Ask questions in plain English without technical expertise. Users can retrieve precise results from SQL databases using simple, conversational language.",
    gradient: "from-purple-500 to-violet-500",
    stats: ["No SQL Required", "Plain English", "Instant Results"]
  },
  {
    icon: Code,
    title: "SQL Query Transparency",
    description: "See the underlying SQL queries generated by the system. Complete transparency ensures trust and allows you to learn SQL as you query.",
    gradient: "from-violet-500 to-purple-600",
    stats: ["Full Transparency", "Learn SQL", "Trust Built-in"]
  },
  {
    icon: Zap,
    title: "Real-Time Responses",
    description: "Get instant accurate answers that work seamlessly with large and complex datasets. No waiting, no delays - just results.",
    gradient: "from-purple-600 to-violet-600",
    stats: ["Lightning Fast", "Big Data Ready", "Zero Delays"]
  },
  {
    icon: Settings,
    title: "Customizable Functionality",
    description: "Tailored solutions with custom filters and workflows to match your unique business requirements and operational needs.",
    gradient: "from-violet-600 to-purple-500",
    stats: ["Custom Filters", "Your Workflow", "Fully Tailored"]
  }
];

export default function DBDashbotFeatures() {
  const sectionRef = useRef<HTMLElement>(null);
  const leftRef = useRef<HTMLDivElement>(null);
  const rightRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const ctx = gsap.context(() => {
      const panels = gsap.utils.toArray<HTMLElement>('.feature-panel');

      ScrollTrigger.create({
        trigger: sectionRef.current,
        start: "top top",
        end: () => `+=${rightRef.current?.offsetHeight || 0}`,
        pin: leftRef.current,
        pinSpacing: false,
      });

      panels.forEach((panel) => {
        gsap.from(panel, {
          opacity: 0,
          x: 100,
          scale: 0.9,
          scrollTrigger: {
            trigger: panel,
            start: "top 80%",
            end: "top 30%",
            scrub: 1,
            toggleActions: "play none none reverse"
          }
        });
      });

    }, sectionRef);

    return () => ctx.revert();
  }, []);

  return (
    <section ref={sectionRef} className="relative bg-gradient-to-b from-[#0E0918] to-[#1a0f2b] overflow-hidden">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid lg:grid-cols-2 gap-12 min-h-screen items-start">
          <div ref={leftRef} className="lg:sticky lg:top-24 py-24">
            <div className="space-y-6">
              <div className="inline-block px-4 py-2 bg-white/5 backdrop-blur-sm border border-white/10 rounded-full">
                <span className="text-sm font-medium text-gray-300">Key Features</span>
              </div>
              <h2 className="text-3xl md:text-4xl font-bold text-white leading-tight">
                Powerful AI-Driven <span className="text-purple-500">Capabilities</span>
              </h2>
              <p className="text-lg text-gray-400 leading-relaxed">
                Transform your database interactions with intelligent natural language processing and real-time insights.
              </p>

              {/* <div className="flex items-center space-x-4 pt-8">
                <div className="flex -space-x-2">
                  {[1, 2, 3, 4].map((i) => (
                    <div key={i} className="w-10 h-10 rounded-full bg-gradient-to-br from-purple-500 to-violet-600 border-2 border-[#0E0918]"></div>
                  ))}
                </div>
                <div className="text-sm text-gray-400">
                  <span className="text-white font-semibold">500+</span> businesses using DBDashbot
                </div>
              </div> */}
            </div>
          </div>

          <div ref={rightRef} className="py-24 space-y-8">
            {features.map((feature, index) => {
              const Icon = feature.icon;
              return (
                <div
                  key={index}
                  className="feature-panel"
                >
                  <div className="group bg-white/5 backdrop-blur-xl border border-white/20 rounded-3xl p-8 hover:border-purple-500/50 transition-all duration-500 hover:shadow-2xl hover:shadow-purple-500/20">
                    <div className="flex items-start justify-between mb-6">
                      <div className={`w-16 h-16 bg-gradient-to-br ${feature.gradient} rounded-2xl flex items-center justify-center group-hover:scale-110 transition-transform duration-300`}>
                        <Icon className="w-8 h-8 text-white" strokeWidth={2} />
                      </div>
                      <div className="text-right">
                        <span className="text-4xl font-bold text-white/10">0{index + 1}</span>
                      </div>
                    </div>

                    <h3 className="text-2xl font-bold text-white mb-4 group-hover:text-purple-300 transition-colors">
                      {feature.title}
                    </h3>

                    <p className="text-gray-400 leading-relaxed mb-6">
                      {feature.description}
                    </p>

                    <div className="flex flex-wrap gap-2">
                      {feature.stats.map((stat, idx) => (
                        <span key={idx} className="px-3 py-1 bg-purple-500/20 border border-purple-500/30 rounded-full text-xs text-purple-300">
                          {stat}
                        </span>
                      ))}
                    </div>

                    <div className="absolute inset-x-0 bottom-0 h-1 bg-gradient-to-r from-transparent via-purple-500 to-transparent opacity-0 group-hover:opacity-100 transition-opacity"></div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </section>
  );
}
